services:
  - type: web
    name: brigade-telegram-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python bot.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: brigade-telegram-bot
          property: url
